126 list item
defenseunicorns/UnicornUI pull request #128
Opened 2023-02-14 20:16 UTC by TristanHoladay

2023-02-24 21:08 UTC, TristanHoladay commented
Thinking about the merit of using event dispatchers for ListItem responding to adornment (child) events. Though it does look like, according to Rich Harris, allowing for default event bubbling is an acceptable approach. 

https://stackoverflow.com/questions/56857853/is-it-possible-to-make-a-child-component-inside-a-slot-to-send-data-to-his-paren

2023-03-01 22:51 UTC, Madeline-UX requested changes
- Would like to meet to align language around list vs list item so we can make sure the design file is using the same vocabulary. 
-  icons and the checkboxes need to respond to dark theme
<img width="324" alt="Screenshot 2023-03-01 at 4 48 15 PM" src="https://user-images.githubusercontent.com/92826525/222283334-242fc884-59cb-4db3-997e-ea15b41f924a.png">
- Nested list items show a nested item that does not align with the other list items
<img width="319" alt="Screenshot 2023-03-01 at 4 47 39 PM" src="https://user-images.githubusercontent.com/92826525/222283475-7f1eeb70-32a8-49b7-a1d2-d418abb115fc.png">
- Would like to see more examples of the variants.

2023-03-03 22:00 UTC, Madeline-UX requested changes
- [x] Move List component documentation to the bottom of page

- [ ] Change page name to List item

- [ ] Change "The ListItem is the true workhorse of List. It wraps your text as well as adornments, like icons, icon buttons, images, checkboxes, etc..." to "The ListItem is the base component of any List. A list item is used to wrap text and adornments into a single component. List item adornment icons, icon buttons, images, checkboxes, and avatars."

- [ ] Update List item flow/examples to this outline

- List Item
   - Props
      - Text
      - Variant
      - Secondary text
      - Selected
      - Disabled
      - Divider
      - Disabled Gutters
- Variants:
   - Simple
   - Icon
   - Avatar
- Slots
    - Describe Slots
   - Examples
      - Leading Icon
      - Icon
      - Checklist
      - Avatar
   - Trailing Action (Explanation)
      - Icon
      - Checkbox
      - Radio button
   - Nested
      - Examples of nested list

2023-03-14 18:36 UTC, Madeline-UX approved these changes

2023-03-15 16:09 UTC, Madeline-UX approved these changes

2023-03-15 16:35 UTC, mike-winberry commented on changelog.md
> +- Three named slots: leadingAdornmnt, trailingAdornment, nested
typo: leadingAdornment

2023-03-15 16:37 UTC, mike-winberry commented on changelog.md
Update with ssx props and box if exists.

2023-03-15 16:41 UTC, mike-winberry commented on uui/src/lib/List/List.svelte
> +  class="mdc-deprecated-list {$$restProps.class || ''} {disablePadding ? 'disabled-padding' : ''}"
Lets add "list" as  a class just for continuity. I want to move away from mdc for the users (it should still be there just want to alleviate the need for users to use the mdc classes)

2023-03-15 16:43 UTC, mike-winberry commented on uui/src/lib/List/List.svelte
> +  ssx={{
need to merge user ssx from $$restProps or the users ssx wont be applied.

2023-03-15 16:46 UTC, mike-winberry commented on uui/src/lib/List/ListItem.svelte
> +
delete this empty line

2023-03-15 16:47 UTC, mike-winberry commented on uui/src/lib/List/ListItem.svelte
Wrap in box and open to ssx

2023-03-15 16:47 UTC, mike-winberry commented on uui/src/lib/List/ListItem.types.d.ts
List item should extend box props.

2023-03-15 16:49 UTC, mike-winberry commented on uui/src/lib/List/ListItemCheckbox.svelte
wrap in box and boxprops

2023-03-15 16:49 UTC, mike-winberry commented on uui/src/lib/List/ListItemCheckbox.types.d.ts
Box props

2023-03-15 21:32 UTC, TristanHoladay commented on uui/src/lib/List/ListItemCheckbox.svelte
Running into style issues with converting checkbox into Box. Will do this within the #13.

2023-03-15 21:32 UTC, TristanHoladay commented on uui/src/lib/List/ListItemCheckbox.types.d.ts
Will do this update in #13 when ListItemCheckbox is extracted out as a general checkbox.

2023-03-15 22:29 UTC, mike-winberry approved these changes

2023-03-15 22:29 UTC, merged