#203 -- Missing Disabled Prop on TextField Example
defenseunicorns/UnicornUI pull request #205
Opened 2023-04-17 13:49 UTC by TristanHoladay

TextField example in docs was labeled as disabled but was missing the disabled prop and was therefore allowing input and interaction.

2023-04-19 18:14 UTC, mike-winberry requested changes
Can we update to more appropriately show the disabled state using the on-disabled/disabled theme values to visually show that it is disabled rather than just making it non-functional.

2023-04-19 18:28 UTC, TristanHoladay commented
This is the current styling for disabled states:

// Disabled State Classes
  .mdc-text-field--disabled {
    @include mdc-text-field-disabled-outline-color(var(--disabled));
    @include mdc-text-field-disabled-ink-color(var(--disabled));
    @include mdc-text-field-disabled-label-color(var(--disabled));

    &:not(.mdc-text-field--outlined) {
      @include mdc-text-field-disabled-fill-color(var(--disabled));
      @include mdc-text-field-disabled-bottom-line-color(var(--disabled));
      @include mdc-text-field-disabled-ink-color(var(--on-disabled));
      @include mdc-text-field-disabled-label-color(var(--on-disabled));
    }
  }

I wonder if the disabled / on-disabled theme colors might not be set to the desired color in the default palettes?

2023-04-20 16:15 UTC, mike-winberry commented
Red is a built in color that exists at build time. Try using another theme color from the default theme and see what happens.

2023-04-20 18:52 UTC, TristanHoladay commented
with `--success` :

<img width="232" alt="Screenshot 2023-04-20 at 12 41 57 PM" src="https://user-images.githubusercontent.com/40547442/233459959-8c46942c-c9f8-4ec0-8c45-faf7dd251608.png">

with `--info`:

<img width="224" alt="Screenshot 2023-04-20 at 12 50 43 PM" src="https://user-images.githubusercontent.com/40547442/233460339-06052dc2-c452-44a7-a7e4-ccc1c6929b77.png">


with `--disabled` and `--on-disabled` for filled text field:
<img width="239" alt="Screenshot 2023-04-20 at 12 45 58 PM" src="https://user-images.githubusercontent.com/40547442/233460097-128ce454-2a5c-4079-8856-8c54c06a6915.png">

with `--disabled` as outlined textfield outline and `--on-disable` for label / value:

<img width="217" alt="Screenshot 2023-04-20 at 12 45 52 PM" src="https://user-images.githubusercontent.com/40547442/233460604-47b870c7-0cb0-4390-b116-943a7f1db871.png">

2023-04-20 19:22 UTC, mike-winberry commented
Yeah those look good on the outlined we may want to flip them on the filled one.

2023-04-21 14:49 UTC, mike-winberry approved these changes

2023-04-21 14:52 UTC, merged